services:
  php:
    # image: yoanbernabeu/symfony-dev-container:latest
    # décommentez la ligne suivante si vous souhaitez utiliser un Dockerfile personnalisé
    build:
      context: ./docker
    # décommentez la ligne suivante si vous souhaitez exécuter ceci dans un environnement de production
    # restart: always
    container_name: QuaiAntique
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
      - "443:443/udp" # HTTP/3
    volumes:
      - ./app:/app
      - caddy_data:/data
      - caddy_config:/config
    # commentez la ligne suivante en production, elle permet d'avoir de beaux logs lisibles en dev
    tty: true
    environment:
      DATABASE_URL: ${DATABASE_URL}

  db:
    image: postgres
    container_name: QuaiAntiqueDB
    restart: always
    environment:
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: QuaiAntiqueDB
    volumes:
      - db_data:/var/lib/postgresql/data


# Volumes nécessaires pour les certificats et la configuration de Caddy
volumes:
  caddy_data:
  caddy_config: 
  db_data: