vich_uploader:
    db_driver: orm

    metadata:
        type: attributes

    mappings:
       products:
           uri_prefix: /images/dishes
           upload_destination: '%kernel.project_dir%/public/images/dishes'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
       gallery:
           uri_prefix: /images/gallery
           upload_destination: '%kernel.project_dir%/public/images/gallery'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
